# Generated by Django 4.0.4 on 2022-05-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AOHI_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
