# Generated by Django 4.0.4 on 2022-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOHI_auth', '0002_rename_phone_number_accounts_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
    ]
