# Generated by Django 4.0.4 on 2022-05-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOHI_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=30)),
                ('lastname', models.CharField(blank=True, db_index=True, max_length=30)),
                ('phone', models.CharField(db_index=True, max_length=14)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=50, verbose_name='email address')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Donations',
                'db_table': 'Donations',
            },
        ),
    ]
