# Generated by Django 4.0.4 on 2022-05-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOHI_users', '0002_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptioninfo',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
