# Generated by Django 4.0.4 on 2022-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=30)),
                ('lastname', models.CharField(blank=True, db_index=True, max_length=30)),
                ('dob', models.DateField()),
                ('picture', models.ImageField(default='user.png', null=True, upload_to='uploaded/')),
                ('status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Orphans',
                'db_table': 'Orphans',
            },
        ),
    ]
