# Generated by Django 4.0.4 on 2022-05-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOHI_admin', '0003_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphans',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True),
        ),
    ]
