# Generated by Django 4.0.4 on 2022-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOHI_admin', '0004_orphans_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphans',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
