# Generated by Django 4.0.4 on 2022-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOHI_admin', '0006_requestadoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestadoption',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
    ]
